KeychainMDIP/kc

doc/CLI-user-manual/README.md
Intended as a review for #60 before it was merged. The first few commits are specific and documented, followed by a general copy edit.
=> Copy Edit for User Manual

doc/CLI-user-manual/10-voting.md, doc/CLI-user-manual/README.md
=> Document Voting

Dockerfile.keymaster, btc-mediator.js, db-json.js, kc-app/src/App.js, kc-app/src/keymaster-sdk.js, keychain-cli.js, keymaster-api.js, keymaster-sdk.js, keymaster.js, keymaster.test.js, tess-mediator.js, workflow.js
Adds an optional name param to backupId() so that the keymaster web app can backup the selected ID rather than the current ID.
=> Backup selected ID

.gitignore, admin-cli.js, gatekeeper-api.js, gatekeeper-lib.js, gatekeeper-sdk.js, gatekeeper.test.js, hyperswarm-mediator.js, keychain-cli.js, keymaster-lib.js, keymaster.test.js
hyperswarm-mediator refactored to improve syncing performance
- On connection, the node will send a 'sync' message to the other node
- When a node receives a 'sync' message, it shares its entire DID db as a single batch to the requesting node
- When a node receives a 'batch' messages, it imports the batch in chunks of 100 events unless it has previously imported the same chunk
- In parallel, the mediator queries its gatekeeper's hyperswarm queue for new events
- If it discovers any events, it batches them and sends them to all its connected nodes with a 'queue' message
- When a node receives a 'queue' event, it relays it to all its connections and imports the events
Additionally, the gatekeeper import functions were consolidated into a single importBatch function
=> Improve syncing

tess-mediator.js
This fixes an issue in tess-mediator where it was creating a batch DID from the TESS queue, but the TESS txn would fail due to insufficient funds in the TESS wallet so it would keep creating an identical batch on every export cycle.
Now it checks for sufficient TESS funds (at least 1 TESS) before creating the batch.
=> Avoid duplicate batches

keymaster-lib.js, keymaster.test.js
updateDID and revokeDID will now sign with DID controller keys instead of the current ID's keys
=> Refactored updateDID and revokeDID

.github/workflows/unit-test.yml, package.json
Enables code coverage reporting for unit tests. Also pushes reports to coveralls. Next PR will add coverall badge in README.
=> Activate code coverage reporting

README.md
=>  Add coverall badge in README for coverage status

kc-app/src/KeymasterUI.js, kc-app/src/keymaster-sdk.js, keymaster-api.js, keymaster-app/src/KeymasterUI.js, rebuildGatekeeper, rebuildKeymaster
Adds a check and fix feature to the Wallet tab
A sample check might respond with a report that some invalid or deleted DIDs were found in the wallet.
If the user proceeds with the fix, the report will summarize what was removed:
When checked again, the wallet will get a clean report:
=> Added wallet check/fix

README.md, doc/README.md, doc/keychain/clients/cli/10-voting.md
Docs link fixes hotfixing #215
=> link cleanup

.github/workflows/docker-build.yml, .github/workflows/docker-publish.yml
Adds docker container vulnerability scanning.
=> chore: activate container scanning

src/kc-app/src/keymaster-sdk.js, src/keymaster-api.js
**Changes:**
Wallet Routes Update:
A list of original route names with updated ones can be seen [here](https://docs.google.com/spreadsheets/d/1weVA5sFnpCK9ebea8SXIDeRGmZIWqDNyYV2I4x97VYk/edit?gid=2127846769#gid=2127846769)
These changes are proposed to ensure that the API remains intuitive and easy to navigate, especially as the number of endpoints grows. By organizing endpoints around resource names and actions, we make our API more scalable and easier to document.
Impact:
Backward Compatibility: These changes will require updates to existing (if any) clients that consume the modified endpoints.
=> refactor: Updating keymaster route names

src/hyperswarm-mediator.js
Ensure queued operations are relayed only once
=> fix: Clear queue before relaying msg

doc/keychain/clients/cli/README.md
Explains to new `kc` users how to download and run the `kc` repo.
=> Add installaton steps to quickstart page

doc/keychain/library/api/index.mdx, doc/openapi.json
Create API Documentation for Keymaster. Depends on https://github.com/KeychainMDIP/kc-docs/pull/19
=> adds API source JSON and redoc page

src/keymaster-lib.js, src/keymaster.test.js, src/workflow.js
Adds a property named `responder` to the JSON returned by verifyResponse that contains the DID of the agent that created the response.
=> feat: Added responder DID to verifyResponse return values

doc/keychain/clients/cli/07-challenge-responses.md
=> DOCS: add challenge did to verify-response example

doc/keychain/clients/cli/02-wallets.md
=> DOCS: document recovery without explicit DID

src/config.js, src/gatekeeper-api.js, src/kc-app/src/KeymasterUI.js, src/kc-app/src/keymaster-sdk.js, src/keychain-cli.js, src/keymaster-api.js, src/keymaster-app/src/KeymasterUI.js, src/keymaster-app/src/index.js, src/keymaster-app/src/keymaster-lib.js, src/keymaster-lib.js, src/keymaster-sdk.js, src/keymaster.test.js, src/workflow.js
On branch main
Your branch is up to date with 'origin/main'.
Changes to be committed:
modified:   src/keymaster-app/src/KeymasterUI.js
modified:   src/keymaster-app/src/index.js
=> Adds WebUI support for QR code URL and parameters

doc/openapi.json
Removed challenge parameter (deprecated)
=> Updated /response/verify

.github/workflows/docker-build.yml, packages/gatekeeper/src/gatekeeper-lib.js, packages/keymaster/src/db-wallet-json-async.js, packages/keymaster/src/db-wallet-json.js, packages/keymaster/src/keymaster-lib.js, scripts/coverage.sh, scripts/keychain-cli.js, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/index.js, tests/keymaster.test.js
Refactors the Keymaster functions (in lib, api, and sdk) to all be async for consistency.
This is #347 take 2
Also disables the Trivy vulnerability scanner job because it was failing 90% of the time on an internal error
Also adds an async version of the keymaster json wallet. Not currently used because of performance issues TBD.
Also adds unit tests for saveWallet()
=> refactor: Made all keymaster functions async

.github/workflows/docker-build.yml, .github/workflows/docker-publish.yml
This replaces Trivy w/ Anchore for container scanning.
=> ci: replace trivy with anchore

services/mediators/satoshi/src/satoshi-mediator.js
satoshi-mediator now handles the case of importing invalid DIDs by skipping them and trying again later on the next import loop.
=> fix: Handle invalid DIDs on import

.github/workflows/docker-build.yml, .github/workflows/docker-publish.yml
This is the fix/implementation for : https://github.com/KeychainMDIP/kc/issues/378
=> chore: point to dockerhub registry vs ghcr registry

doc/integration_guide.md
Updated as per comments. Thanks for your help!
=> Flaxscrip integration guide 1

packages/keymaster/src/keymaster-lib.js, tests/keymaster.test.js
Moves schema properties under a `schema` label in the `didDocumentData`
Backwards compatible with existing schema DIDs which will be automatically upgraded if they are updated.
=> refactor: Upgrade schemas

services/mediators/hyperswarm/src/hyperswarm-mediator.js
hyperswarm-mediator now ensures all sync messages are smaller than a hard-coded limit of 8MB
=> fix: hyperswarm-mediator limit msg size

.github/workflows/docker-build.yml, .github/workflows/docker-publish.yml, services/mediators/ipfs/src/ipfs-mediator.js
Also adds ipfs-mediator to github workflow (resolves #433)
=> fix: Added exception handling to ipfs-mediator

packages/gatekeeper/src/db-mongodb.js, packages/gatekeeper/src/db-redis.js, packages/gatekeeper/src/gatekeeper-lib.js, tests/gatekeeper.test.js
Adds a missing method to the mongodb interface. I created a new issue #443 to develop integration tests to catch these kinds of db issues
=> fix: Node sync with mongodb

services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
Adds a Messages tab to the UI, with subtabs to Send and Receive encrypted messages from other users.
=> feat: Added messages tab to web wallet

package-lock.json, packages/cipher/package.json, packages/common/package.json, packages/gatekeeper/package.json, packages/ipfs/package.json, packages/keymaster/package.json, services/mediators/hyperswarm/src/config.js
Updated package versions to `0.5.0` and MDIP protocol to `/MDIP/v0.5-beta`
=> chore: Updated package versions and protocol

services/gatekeeper/client/src/App.js, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
TBD keymaster and gatekeeper services should import KeymasterUI react component from the same package, but until then they each have an identical copy of the component.
=> refactor: Encryption parameters

packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, python/keymaster_sdk/src/keymaster_sdk/keymaster_sdk.py, services/keymaster/server/src/keymaster-api.js, tests/keymaster.test.js
Also added new API endpoint for getPoll()
Also added testPoll() and listPolls() and corresponding API endpoints.
Also refactored testSchema(), listSchemas(), testGroup() and listGroups() to use the same patterns.
Also changed API endpoint for unpublishPoll from DELETE to POST.
=> feat: Added poll methods to KeymasterClient

packages/keymaster/src/keymaster-sdk.js, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/keymaster-api.js
Adds version navigation buttons and dropdown to the Identities and DIDs tabs on the web wallet
=> feat: Adds version navigation to web wallet

LICENSE
=> fix copyright ownership

browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/popup/PopupContext.tsx, browser/chrome-extension/src/popup/components/AuthTab.tsx, browser/chrome-extension/src/popup/components/DropDownID.tsx, browser/chrome-extension/src/popup/components/IdentitiesTab.tsx, browser/chrome-extension/src/popup/components/PanelHeader.tsx, browser/chrome-extension/src/popup/popup.css, browser/chrome-extension/src/wallet/WalletUI.tsx
- Add drop down ID selection on every tab
- Add mnemonic to wallet page
- Show wallet contents on wallet page
=> feat: multi-tab drop down ID selection

browser/chrome-extension/package-lock.json, browser/chrome-extension/package.json, browser/chrome-extension/src/offscreen/offscreen.html, browser/chrome-extension/src/popup/PopupContext.tsx, browser/chrome-extension/src/viewer/JsonViewer.tsx, browser/chrome-extension/src/viewer/viewer.tsx, browser/chrome-extension/src/wallet/WalletUI.tsx, browser/chrome-extension/webpack.common.js
Adds a JSON viewer to the Chrome extension rather than just have the JSON in plaintext.
Resolve: https://github.com/KeychainMDIP/kc/issues/552
=> feat: Add JSON viewer to extension

browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/popup/PopupContext.tsx, browser/chrome-extension/src/popup/components/AuthTab.tsx, browser/chrome-extension/src/popup/components/CredentialsTab.tsx, browser/chrome-extension/src/popup/components/DIDsTab.tsx, browser/chrome-extension/src/popup/components/DropDownID.tsx, browser/chrome-extension/src/popup/components/PanelHeader.tsx, browser/chrome-extension/src/popup/components/WarningModal.tsx, browser/chrome-extension/src/popup/popup.css, browser/chrome-extension/src/viewer/JsonViewer.tsx, packages/gatekeeper/types/index.d.ts, packages/keymaster/types/index.d.ts
- Adds a DID list to the Chrome browser extension
- Update the JSON viewer to shows doc version for any DID viewed with resolveDID.
- Add resolve DID icon to the current ID
- Turn remove warning modal into a component
- Resolves https://github.com/KeychainMDIP/kc/issues/553
=> feat: add DID list to extension

docker-compose.yml, sample.env, services/mediators/hyperswarm/src/config.js, services/mediators/hyperswarm/src/hyperswarm-mediator.js
=> feat: Added export interval to hyperswarm config

packages/gatekeeper/src/gatekeeper.js, tests/gatekeeper.test.js
=> feat: Added operation size limit

packages/gatekeeper/src/gatekeeper.js, services/gatekeeper/server/src/gatekeeper-api.js
=> feat: Added events queue to server status

.github/workflows/build-chrome-extension.yml
Resolves: https://github.com/KeychainMDIP/kc/issues/563
=> feat: add browser extension build GitHub workflow

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/browser.tsx, browser/chrome-extension/src/browser/components/BrowserHeader.tsx, browser/chrome-extension/src/browser/components/CredentialForm.tsx, browser/chrome-extension/src/browser/components/IssueTab.tsx, browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/popup/popup.tsx, browser/chrome-extension/src/shared/IdentitiesTab.tsx, browser/chrome-extension/src/shared/contexts/ContextProviders.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, browser/chrome-extension/src/shared/extension.css, browser/chrome-extension/src/shared/sharedScripts.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/589
- Adds light and dark themes to the extension.
- Browser remember whether the menu was open
- Use getSchema for the credential form
=> feat: add themes to Chrome browser extension

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/SchemaTab.tsx, browser/chrome-extension/src/popup/components/DIDsTab.tsx, browser/chrome-extension/src/shared/contexts/WalletProvider.tsx
- Resolves https://github.com/KeychainMDIP/kc/issues/605
=> feat: Chrome browser extension add schema tab

services/mediators/hyperswarm/src/hyperswarm-mediator.js
Also refactored shareDb to handle case of >100k DIDs in db without out-of-memory crash
=> fix: Added sync queue to hyperswarm-mediator

services/gatekeeper/server/README.md, services/gatekeeper/server/src/gatekeeper-api.js
Same for status update interval
=> feat: Disable gc when interval set to 0

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/JsonViewer.tsx, browser/chrome-extension/src/browser/components/MnemonicModal.tsx, browser/chrome-extension/src/browser/components/WalletTab.tsx, browser/chrome-extension/src/shared/HeldTab.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, packages/keymaster/types/index.d.ts
- Resolves https://github.com/KeychainMDIP/kc/issues/609
- Centralise handling of URL params
- Fix JSON viewer issue when populated via URL were view would return to previous content when switching tabs
=> feat: Chrome extension complete wallet tab

browser/chrome-extension/package.json, browser/chrome-extension/src/browser/components/MnemonicModal.tsx, browser/chrome-extension/src/static/manifest.json
- Set the Chrome browser extension to v1.0.0
=> chore: set Chrome extension to v1.0.0

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/JsonViewer.tsx, browser/chrome-extension/src/browser/components/WalletTab.tsx, browser/chrome-extension/src/shared/HeldTab.tsx
- Resolves https://github.com/KeychainMDIP/kc/issues/645
=> feat: extension make JSON wallet view browsable

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/GroupsTab.tsx, browser/chrome-extension/src/browser/components/IssuedTab.tsx, browser/chrome-extension/src/browser/components/JsonViewer.tsx, browser/chrome-extension/src/browser/components/WalletTab.tsx, browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/shared/HeldTab.tsx, browser/chrome-extension/src/shared/contexts/CredentialsProvider.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, browser/chrome-extension/src/shared/extension.css, packages/keymaster/types/index.d.ts
- Resolves https://github.com/KeychainMDIP/kc/issues/611
- Make JSON viewers content persistent so they do not wipe when you move away and return.
- Open JSON viewer DID links on the wallet page in the dedicated JSON viewer.
- Fix bug on issued tab where pressing decrypt then resolve enables the update button.
- Move JSON Viewer options into the JSON viewer.
- Add JSON viewer on issued tab when resolving credentials.
=> feat: add group tab to Chrome browser extension

browser/chrome-extension/tsconfig.json, browser/chrome-extension/webpack.common.js, package-lock.json, package.json, packages/cipher/package.json, packages/cipher/src/cipher-node.ts, packages/cipher/src/cipher-web.ts, packages/cipher/src/types.ts, packages/cipher/tsconfig.json, packages/cipher/types/index.d.ts, packages/common/package.json, packages/common/src/errors.ts, packages/common/src/utils.ts, packages/common/tsconfig.json, packages/common/types/index.d.ts, packages/gatekeeper/package.json, packages/ipfs/package.json, packages/keymaster/package.json, packages/keymaster/src/keymaster-lib.js, tsconfig.json
- Resolve https://github.com/KeychainMDIP/kc/issues/679
=> feat: convert Cipher and common libs to TypeScript

.github/workflows/swagger-jsdoc.yml, browser/chrome-extension/tsconfig.json, browser/chrome-extension/webpack.common.js, doc/gatekeeper-api.json, jest.config.js, package-lock.json, package.json, packages/cipher/src/cipher-node.ts, packages/cipher/src/cipher-web.ts, packages/gatekeeper/package.json, packages/gatekeeper/src/gatekeeper-client.ts, packages/gatekeeper/src/gatekeeper.ts, services/gatekeeper/server/src/gatekeeper-api.js, tests/gatekeeper-client.test.ts, tests/gatekeeper.test.ts, tsconfig.json
- Resolves https://github.com/KeychainMDIP/kc/issues/690
=> feat: convert GatekeeperClient to TypeScript

doc/keymaster-api.json, packages/keymaster/src/keymaster-sdk.js, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/App.css, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster-client.test.js
Adds image asset support to the server wallet to test KeymasterClient and the keymaster API. 
(Continuation of #710)
=> feat: Add image assets to server wallet

Dockerfile.gatekeeper, Dockerfile.keymaster, doc/deployment/index.mdx, packages/gatekeeper/src/gatekeeper.ts, packages/ipfs/package.json, services/gatekeeper/server/package-lock.json, services/gatekeeper/server/package.json, services/gatekeeper/server/src/gatekeeper-api.ts, services/gatekeeper/server/tsconfig.json, services/keymaster/server/package-lock.json, services/keymaster/server/package.json, services/keymaster/server/src/keymaster-api.ts, services/keymaster/server/tsconfig.json, swaggerConf.js
Resolves: https://github.com/KeychainMDIP/kc/issues/719
=> feat: convert APIs to TypeScript

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/BrowserHeader.tsx
Resolves: https://github.com/KeychainMDIP/kc/issues/739
=> fix: extension make header and panel transition together

doc/keymaster-api.json, packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, scripts/keychain-cli.js, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/keymaster-api.ts
Also adds the rotate keys feature to the web wallet
=> fix: CLI rotate-keys command

docker-compose.yml, rebuildGatekeeper, rebuildKeymaster, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, tests/keymaster-client.test.ts
Adds update image feature, and ability to navigate image versions.
Also resolves #750
=> feat: Adds update image to web wallet

tests/cli-tests/test_cli_backup_id.expect, tests/cli-tests/test_cli_create_id.expect, tests/cli-tests/test_cli_create_schema_template.expect, tests/cli-tests/test_cli_get_credential_by_id.expect, tests/cli-tests/test_cli_get_schema.expect, tests/cli-tests/test_cli_list_credentials.expect, tests/cli-tests/test_cli_list_dids.expect, tests/cli-tests/test_cli_list_issue_credentials.expect, tests/cli-tests/test_cli_list_schema.expect, tests/cli-tests/test_cli_resolve_id.expect, tests/cli-tests/test_cli_reveal_credentials.expect, tests/cli-tests/test_cli_revoke_credentials.expect, tests/cli-tests/test_cli_rotate_keys.expect, tests/cli-tests/test_cli_show_mnemonic.expect, tests/cli-tests/test_cli_validate_help.expect
Adds more CLI tests, and fixes a few errors where we don't exit properly. I have validated these work on Ubuntu as well.
=> test: add more cli tests

tests/cli-tests/hyperswarm/test_cli_import_wallet.expect, tests/cli-tests/test_cli_create_wallet.expect, tests/cli-tests/test_cli_get_schema.expect, tests/cli-tests/test_cli_publish_credential.expect, tests/cli-tests/test_cli_recover_id.expect, tests/cli-tests/test_cli_resolve_id.expect, tests/cli-tests/test_cli_show_wallet.expect
Adds two more cli tests and updates some validation logic to verify key:values for some tests are checking properly.
=> test: update validation for tests and add recover_id and publish credentials cli test

services/explorer/src/App.tsx, services/explorer/src/components/Events.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/798
=> fix: load events as soon as Gatekeeper is ready

services/explorer/package-lock.json, services/explorer/package.json, services/explorer/src/App.tsx, services/explorer/src/components/Header.tsx, services/explorer/src/components/JsonViewer.tsx, services/explorer/src/main.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/797
=> feat: add back button support to the Chrome ext

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/DocumentTab.tsx, browser/chrome-extension/src/browser/components/JsonViewer.tsx, browser/chrome-extension/src/browser/components/VersionNavigator.tsx, browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/shared/contexts/CredentialsProvider.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/781
=> feat: chrome extension add document support

browser/chrome-extension/src/browser/components/DocumentTab.tsx, browser/chrome-extension/src/browser/components/ImageTab.tsx
- Resolve: https://github.com/KeychainMDIP/kc/issues/814
=> feat: Chrome extension add image update ability

packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/824
=> chore: createSchema set correct type for options

packages/keymaster/src/types.ts, tests/keymaster.test.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/829
=> Update Challenge type to include any other fields

browser/chrome-extension/webpack.common.js, package-lock.json, packages/cipher/package.json, packages/cipher/rollup.cjs.config.js, packages/cipher/tsconfig.json, packages/common/package.json, packages/common/rollup.cjs.config.js, packages/common/tsconfig.json, packages/gatekeeper/package.json, packages/gatekeeper/rollup.cjs.config.js, packages/gatekeeper/tsconfig.json, packages/ipfs/package.json, packages/ipfs/rollup.cjs.config.js, packages/ipfs/tsconfig.json, packages/keymaster/package.json, packages/keymaster/rollup.cjs.config.js, packages/keymaster/tsconfig.json
- Resolves: https://github.com/KeychainMDIP/kc/issues/828
=> feat: implement CJS and ESM dual build in packages

browser/chrome-extension/src/browser/components/JsonViewer.tsx, services/explorer/src/components/JsonViewer.tsx
- Resolve: https://github.com/KeychainMDIP/kc/issues/803
- Also adds TBTC links to the Chrome ext JSON viewer
=> feat: explorer/extension JsonView add TBTC block and TX links

services/explorer/server.js
- Resolves: https://github.com/KeychainMDIP/kc/issues/833
=> fix: search server use wildcard for URLs

packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/847
=> fix: correct option arg type

.github/workflows/release-publish.yml
Adds latest tag when we build and push for release.
=> ci: add latest tag when we build and push docker images for release

packages/keymaster/src/keymaster.ts, tests/keymaster.test.ts
This PR fixes group vault key rotation issues and enhances support for adding members and items after key rotation.
- Added tests to verify that group vault members and items remain accessible after key rotation.
- Refactored decryption logic in the Keymaster class by introducing a helper function (decryptWithDerivedKeys) to centralize key derivation decryption for rotated keys.
=> fix: GroupVault handles key rotation

browser/chrome-extension/src/browser/components/DocumentTab.tsx, browser/chrome-extension/src/browser/components/GroupsTab.tsx, browser/chrome-extension/src/browser/components/ImageTab.tsx, browser/chrome-extension/src/browser/components/IssueTab.tsx, browser/chrome-extension/src/browser/components/IssuedTab.tsx, browser/chrome-extension/src/browser/components/JsonViewer.tsx, browser/chrome-extension/src/browser/components/SchemaTab.tsx, browser/chrome-extension/src/browser/components/WalletTab.tsx, browser/chrome-extension/src/popup/components/AuthTab.tsx, browser/chrome-extension/src/popup/components/DIDsTab.tsx, browser/chrome-extension/src/popup/components/MessageReceiveTab.tsx, browser/chrome-extension/src/popup/components/MessageSendTab.tsx, browser/chrome-extension/src/shared/DropDownID.tsx, browser/chrome-extension/src/shared/HeldTab.tsx, browser/chrome-extension/src/shared/IdentitiesTab.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, browser/chrome-extension/src/shared/contexts/WalletProvider.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/835
- Refactors setError to extract the error in a single location.
=> fix: reset doc/image max version when changing asset

demo/commonjs-demo/package-lock.json, demo/commonjs-demo/package.json, demo/commonjs-demo/src/demo.ts, demo/commonjs-demo/tsconfig.json, packages/cipher/package.json, packages/cipher/rollup.cjs.config.js, packages/common/package.json, packages/common/rollup.cjs.config.js, packages/gatekeeper/package.json, packages/gatekeeper/rollup.cjs.config.js, packages/ipfs/package.json, packages/ipfs/rollup.cjs.config.js, packages/keymaster/package.json, packages/keymaster/rollup.cjs.config.js
- Resolves: https://github.com/KeychainMDIP/kc/issues/851
=> fix: add typings for CommonJS

packages/keymaster/src/keymaster-client.ts, services/gatekeeper/client/package-lock.json, services/gatekeeper/client/package.json, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/package-lock.json, services/keymaster/client/package.json, services/keymaster/client/src/KeymasterUI.js, start-node
Also adds icons consistent with the Chrome browser extension.
=> feat: Adds vaults to web wallet assets

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/CloneAssetTab.tsx, browser/chrome-extension/src/browser/components/DocumentTab.tsx, browser/chrome-extension/src/browser/components/GroupVaultTab.tsx, browser/chrome-extension/src/browser/components/GroupsTab.tsx, browser/chrome-extension/src/browser/components/ImageTab.tsx, browser/chrome-extension/src/browser/components/NamedDIDs.tsx, browser/chrome-extension/src/browser/components/SchemaTab.tsx, browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/popup/components/MessageSendTab.tsx, browser/chrome-extension/src/shared/IdentitiesTab.tsx, browser/chrome-extension/src/shared/extension.css
- Resolves: https://github.com/KeychainMDIP/kc/issues/887
- Add assets menu and move asset types under it
- Update popup drop down menu
- Add clone assets to assets menu
- Move named DIDs to browser window
- Add revoke and transfer to named DIDs
- Make all named lists ordered
- Auto edit from drop down on schemas and groups
- Add copy DID, rename and resolve to all asset tabs
=> chore: update browser extension

.github/workflows/swagger-jsdoc.yml, browser/chrome-extension/src/background/background.ts, browser/chrome-extension/src/browser/browser.tsx, browser/chrome-extension/src/browser/components/GroupVaultTab.tsx, browser/chrome-extension/src/browser/components/NamedDIDs.tsx, browser/chrome-extension/src/shared/DisplayDID.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/894
- Add Autocomplete to vault members
- Add icons to named DIDs
- Add type filter to named DIDs
=> fix: Chrome extension avoid URL data limits. Minor improvements.

browser/chrome-extension/src/background/background.ts, browser/chrome-extension/src/contentScript/contentScript.ts, browser/chrome-extension/src/offscreen/offscreen.ts, browser/chrome-extension/src/popup/popup.tsx, browser/chrome-extension/src/shared/contexts/ContextProviders.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/671
=> feat: Chrome extension add accept credential links

Dockerfile.explorer, Dockerfile.search-server, services/search-server/src/index.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/846
=> fix: explorer/search-server errors on shutdown

services/search-server/src/db/sqlite.ts, services/search-server/src/index.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/898
Example JQL queries set in the POST body as raw JSON for the following new /query endpoint.
http://localhost:4002/api/v1/query
Query
```
{
"where": {
"mdip.type": { "$in": ["agent"] }
}
}
```
Result
```
[
"did:test:z3v8Auahqe6r8TLwNMwaYBzgaJ99CQmwUbFjzRqcePzX3MCxyxN",
"did:test:z3v8Auai7RfjWDRtc7T1vKHAPgEy9MqY54Svu1yQLdJsyqCU3JU",
"did:test:z3v8Auaa1VokNK8mEiTTYAChvSCwubWWhB5wiFjvcYPru8N72Yv",
...
"did:test:z3v8AuadSHArowwoNeaAcPNBkVvdwmxrx2r9sXcgYxfAr83tKxL",
"did:test:z3v8AuaZHovdinWT165yehtg75trUM2jbS3sPRKWt9Hotdz342f",
"did:test:z3v8AuafmLnqAqTufuTqYine12A4owsx4D9wQWHzWqG3RkfQsiV"
]
```
Query
```
{
"where": {
"didDocumentData.manifest.*.credential.food": {
"$in": ["chicken"]
}
}
}
```
Result
```
[ …
```
=> feat: add query endpoint to search server

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/AssetsTab.tsx, browser/chrome-extension/src/browser/components/CredentialsTab.tsx, browser/chrome-extension/src/browser/components/DmailDialog.tsx, browser/chrome-extension/src/browser/components/DmailTab.tsx, browser/chrome-extension/src/browser/components/DocumentTab.tsx, browser/chrome-extension/src/browser/components/GroupVaultTab.tsx, browser/chrome-extension/src/browser/components/GroupsTab.tsx, browser/chrome-extension/src/browser/components/ImageTab.tsx, browser/chrome-extension/src/browser/components/SchemaTab.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/909
=> feat: Chrome extension add dmail

services/search-server/src/db/sqlite.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/916
Query
```
{
"where": {
"didDocumentData.notice.to[*]": {
"$in": ["did:mdip:z3v8Auac943LJ35nGb4ahnLnV9yCWJLemB8Lnyzt9Z6c4w8rdyM"]
}
}
}
```
Result
```
[
"did:test:z3v8AuaXJc4Px8jTz9BE1jEDwqsLtqPXTcwK6LD42Wjy45WMWdU"
]
```
=> feat: search server add array wildcard support

browser/chrome-extension/src/background/background.ts, browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/DmailTab.tsx, browser/chrome-extension/src/browser/components/NamedDIDs.tsx, browser/chrome-extension/src/browser/components/PollResultsModal.tsx, browser/chrome-extension/src/browser/components/PollTab.tsx, browser/chrome-extension/src/browser/components/SettingsTab.tsx, browser/chrome-extension/src/shared/contexts/CredentialsProvider.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, browser/chrome-extension/src/shared/contexts/WalletProvider.tsx, browser/chrome-extension/webpack.common.js, jest.config.js, packages/keymaster/package.json, packages/keymaster/rollup.cjs.config.js, packages/keymaster/src/keymaster.ts, services/search-server/src/DidIndexer.ts, tests/keymaster/notice.test.ts, tests/keymaster/poll.test.ts, tsconfig.json
- Resolves: https://github.com/KeychainMDIP/kc/issues/924
- Add notices for polls and ballots
=> feat: browser extension add polls

.github/workflows/docker-build-test.yml, .github/workflows/e2e-test-report.yml, tests/run_cli_tests.sh
Add additional artifacts we upload from the E2E test results. Also adds a new workflow which parses that .xml and displays it in the PR.
=> test: update e2e reporter to generate junit xml file to be used for reporting

browser/chrome-extension/src/browser/components/DmailTab.tsx, browser/chrome-extension/src/browser/components/PollTab.tsx, doc/keymaster-api.json, package-lock.json, packages/keymaster/src/keymaster-client.ts, services/gatekeeper/client/src/KeymasterUI.js, services/gatekeeper/client/src/PollResultsModal.jsx, services/gatekeeper/client/src/TextInputModal.jsx, services/keymaster/client/src/KeymasterUI.js, services/keymaster/client/src/PollResultsModal.jsx, services/keymaster/client/src/TextInputModal.jsx, services/keymaster/server/src/keymaster-api.ts, tests/keymaster/client.test.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/889
- Gets notices and new polls and DMails every 30 seconds.
- Replaces window.alert with snackbar popup
=> feat: add polls to web wallet

browser/chrome-extension/src/browser/components/DmailTab.tsx, browser/chrome-extension/src/browser/components/NamedDIDs.tsx, browser/chrome-extension/src/browser/components/PollTab.tsx, browser/chrome-extension/src/shared/contexts/CredentialsProvider.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, browser/chrome-extension/src/shared/contexts/WalletProvider.tsx, packages/keymaster/src/keymaster.ts, services/gatekeeper/client/src/KeymasterUI.js, services/gatekeeper/client/src/WarningModal.jsx, services/keymaster/client/src/KeymasterUI.js, services/keymaster/client/src/WarningModal.jsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/943
- Resolves: https://github.com/KeychainMDIP/kc/issues/948
- Add delete poll to poll vote / view tab
- Disable send ballot until unsent vote available
- Do not populate last vote (only worked for controller)
- Do not add poll from notices if already in name list
- Clear poll vote / view tab when user changes
- Hide voting controls if user cannot vote
- Add voting eligibility icon on poll drop down
=> chore: web/ext update polls

browser/chrome-extension/src/browser/components/DmailTab.tsx, browser/chrome-extension/src/browser/components/DocumentTab.tsx, browser/chrome-extension/src/browser/components/GroupVaultTab.tsx, browser/chrome-extension/src/browser/components/GroupsTab.tsx, browser/chrome-extension/src/browser/components/ImageTab.tsx, browser/chrome-extension/src/browser/components/IssueTab.tsx, browser/chrome-extension/src/browser/components/NamedDIDs.tsx, browser/chrome-extension/src/browser/components/PollTab.tsx, browser/chrome-extension/src/browser/components/SchemaTab.tsx, browser/chrome-extension/src/shared/CopyDID.tsx, browser/chrome-extension/src/shared/CopyResolveDID.tsx, browser/chrome-extension/src/shared/DisplayDID.tsx, browser/chrome-extension/src/shared/DropDownID.tsx, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
- Resolves: https://github.com/KeychainMDIP/kc/issues/953
- Resolves: https://github.com/KeychainMDIP/kc/issues/952
=> chore: ext add copy/resolve component. displays names in group list.

browser/chrome-extension/src/shared/contexts/UIContext.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/954
=> chore: ext improve initial responsiveness

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/components/DmailTab.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/964
- Fix error trying to set active tab before it is available
- Improve performance.
- Skip unnecessary refreshAll() at start
- Populate heldList sooner so everything appears loaded if popup opens on the held tab.
=> feat: extension add revoke to DMail

browser/chrome-extension/src/browser/components/NamedDIDs.tsx
- Resolves: https://github.com/KeychainMDIP/kc/issues/1003
=> feat: Chrome extension add tickbox multi-select to DID list

jest.config.js, packages/inscription/src/inscription.ts, tests/inscription/inscription.test.ts, tsconfig.json
- Resolves: https://github.com/KeychainMDIP/kc/issues/1007
=> chore: add tests for inscription library

packages/keymaster/src/index.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/1041
=> chore: keymaster export AbstractBase
