keychain-cli.js, keymaster.js, keymaster.test.js
This PR adds support for poll voting:
```
poll-create <file> [name]                   Create poll
poll-publish <poll>                         Publish results to poll, hiding ballots
poll-reveal <poll>                          Publish results to poll, revealing ballots
poll-template                               Generate a poll template
poll-unpublish <poll>                       Remove results from poll
poll-update <ballot>                        Add a ballot to the poll
poll-view <poll>                            View poll details
poll-vote <poll> <vote> [spoil]             Vote in a poll
```
The poll requires a roster which is a list of eligible voters. The roster is created separately with group commands:
```
group-add <group> <member>                  Add a member to a group …
```
=> Adds support for voting

keymaster.js, keymaster.test.js
Groups may be added to groups to define a hierarchy.
Groups may not contain themselves (no circular references allowed).
=> Support groups within groups

Dockerfile.btc, admin-cli.js, btc-mediator.js, clean-data.sh, config.js, db-benchmark.js, db-json.js, db-mongodb.js, db-sqlite.js, dc-btc.yml, gatekeeper-sdk.js, gatekeeper.js, gatekeeper.test.js, hyperswarm-mediator.js, keychain-cli.js, keymaster.js, keymaster.test.js, server.js, start-node.sh, stop-node.sh, sync-node.sh, tess-mediator.js, workflow.js
Adds a BTC mediator to the node
- Relies on an external BTC node
- The BTC node must have indexing enabled (`txindex=1`) 
- The BTC node must have RPC access enabled (e.g. `rpcuser=[username]`, `rpcpassword=[password]`, `rpcport=8332`, `rpcbind=0.0.0.0`, `rpcallowip=0.0.0.0/0`) 
- The BTC node should have a wallet loaded on startup (e.g. `wallet=beta`)
- The following environment variables should be define in a local `.env` file:
```
KC_BTC_HOST=localhost
KC_BTC_PORT=8332
KC_BTC_USER=username
KC_BTC_PASS=password
KC_BTC_WALLET=beta
KC_BTC_IMPORT_INTERVAL=1
KC_BTC_EXPORT_INTERVAL=15
KC_BTC_FEE_MIN=0.00001500
KC_BTC_FEE_MAX=0.00020000
KC_BTC_FEE_INC=0.00001000
KC_NODE_ID=satoshi
```
Change the values of the first 5 to correspond to the BTC node configuration.
- `KC_BTC_IMPORT_INTERVAL` …
=> Added btc-mediator

.gitignore, config.js, kc-app/src/App.js, keymaster-api.js
@macterra - I had to make these edits to enable parallel keymaster containers running on their individual ports while sharing a common gatekeeper process.
With this change, I'm able to easily provision new "Keymasters" with the following simple docker compose file. In my current deployment, I put the additional keymasters in seperate ./custodials/account-name folders.
```
version: "3"
services:
keymaster-flaxscrip:
build:
context: ../..
dockerfile: Dockerfile.keymaster
image: keychainmdip/keymaster
environment:
- KC_GATEKEEPER_URL=http://172.17.0.1
- KC_GATEKEEPER_PORT=4224
- KC_KEYMASTER_PORT=4240
volumes:
- ./data:/app/data
ports:
- "4240:4240"
```
=> enables parallel keymasters on individual ports

.github/workflows/docker-publish.yml, admin-cli.js, btc-mediator.js, gatekeeper-api.js, gatekeeper-lib.js, gatekeeper-sdk.js, hyperswarm-mediator.js, tess-mediator.js
Adds garbage collection to hyperswarm-mediator
- gc is triggered at startup, and every 10 minutes after
- a DID is removed from the gatekeeper db if the following criteria are met
- registered on hyperswarm
- type asset (not agent)
- created <24 hours ago
This PR also fixes an issue with clearing registry queues
=> Add hyperswarm DID garbage collection

gatekeeper-lib.js, gatekeeper.test.js
DIDs registered to `local` will no longer be distributed by hyperswarm. Additionally local agents can only create local assets.
=> Fix for local DIDs

admin-cli.js, gatekeeper-lib.js, hyperswarm-mediator.js
Significant refactor of the hyperswarm-mediator to improve resilience
- Connections that haven't pinged in >3 minutes are dropped
- The mediator will reconnect to swarm with a new ID if all connections are dropped
- Adds logging for connection changes
Also includes
- Added `resolve-did` command to admin CLI
- Refactored gatekeeper.generateDoc to ensure DIDs always have a prefix even when resolving a raw suffix DID
- Added verifyDID function to gatekeeper 
- Currently ensures DID can resolve OK as before
- Also ensures non-local assets have non-local controllers, otherwise delete (which fixes a syncing error I was seeing)
- Locally registered DIDs are no longer distributed by the initial DID sync logic
=> Hyperswarm mediator removes stale connections

gatekeeper-lib.js, kc-app/src/KeymasterUI.js, kc-app/src/keymaster-sdk.js, keychain-cli.js, keymaster-api.js, keymaster-app/src/KeymasterUI.js, keymaster-lib.js
Adds buttons to publish, reveal, or unpublish a held credential. Only 2 of the buttons will be enabled at a time because the credential is in one of the 3 states.
=> Added credential pub features to web UI

hyperswarm-mediator.js, kc-app/src/KeymasterUI.js, kc-app/src/keymaster-sdk.js, keychain-cli.js, keymaster-api.js, keymaster-app/src/KeymasterUI.js, keymaster-app/src/keymaster-web.js, keymaster-lib.js, keymaster.test.js
Adds an `Issued` subtab under Credentials with options to Resolve, Decrypt, and Revoke. Revoke will remove the credential from the list.
On the Credentials Held tab, the Remove button will be disabled unless the credential is unpublished
- `check-wallet` reports the number of invalid and deleted DIDs in the wallet
- `fix-wallet` removes invalid and deleted DIDs from the wallet
- `list-issued` returns a list of credentials issued by the current ID
The features to check and fix the wallet were added because of an issue (now fixed) that caused the wallet to fill up with ephemeral DIDs like challenges and responses that become invalid when they are garbage collected.
Another issue discovered and fixed was the hyperswarm-mediator was not properly distributing delete operations (revoke …
=> Add issued credentials to web UI

admin-cli.js, gatekeeper-api.js, gatekeeper-lib.js, gatekeeper-sdk.js, gatekeeper.test.js, keymaster-app/src/cipher-lib.js
Adds 4 new parameters to gatekeeper.getDIDs:
- `updatedAfter` timestamp in ISO format, e.g. "2024-07-01T20:00Z" : return DIDs created or updated after timestamp
- `updatedBefore` timestamp in ISO format : return DIDs created or updated before timestamp
- `confirm` : return only confirmed updates
- `resolve` : return JSON list of resolved docs instead of DIDs
The corresponding API endpoint `/api/v1/did` takes the same parameters:
```
GET /api/v1/did/?updatedAfter=2024-07-01T20:00Z&updatedBefore=2024-07-021T20:00Z&confirm=null&resolve=true
```
=> Added params to getDIDs

.github/workflows/docker-build.yml, .github/workflows/docker-publish.yml
1. This improves maintenance & changes of adding new docker image builds to the CI pipeline. 
2. Also updates the GH actions that are using older node versions. 
3.  Improves build time by about 30-40 seconds as this introduces parallelism, and failure isolation where if one image fails, we are still able to build the rest of the images independently.
=> Refactor docker build push

admin-cli.js, doc/DID-scheme/README.md, gatekeeper-api.js, gatekeeper-lib.js, gatekeeper-sdk.js, gatekeeper.test.js, keychain-cli.js, keymaster-app/src/gatekeeper-sdk.js, keymaster-app/src/keymaster-lib.js, keymaster-lib.js
`resolveDID` options are now specified by name instead of position, e.g.
```
const doc = await resolveDID(operation.signature.signer, { 
atTime: operation.signature.signed, 
confirm: true
});
```
Also adds `dids` parameter to `getDIDs` (defaults to all DIDs). In order to accomodate an array of DIDs, the corresponding gatekeeper endpoint has changed from 
```
GET /api/v1/did
```
to
```
POST /api/v1/dids
```
=> Refactors resolveDID parameters

cipher-lib.js, keymaster-app/src/cipher-lib.js
Fixed cipher-lib for CLI. Also reverted the version of cipher-lib in keymaster-app/src, so the attempt to merge the 2 versions has failed for now. TBD.
=> fix: Fixed backup-wallet for CLI

kc-app/src/KeymasterUI.js, kc-app/src/keymaster-sdk.js, keymaster-api.js, keymaster-app/src/KeymasterUI.js, keymaster-app/src/keymaster-lib.js, keymaster-lib.js
Previously when creating an asset through the web app (group, schema, or credential) it was always registered on the default registry (TESS). Now a dropdown is provided next to the create button to select which registry to use for the asset.
=> feat: Add registry dropdowns to create assets

admin-cli.js, gatekeeper-api.js, gatekeeper-lib.js, gatekeeper-sdk.js, gatekeeper.test.js, keymaster-app/src/gatekeeper-sdk.js
During DID resolution the update operation signatures will only be checked if the verify flag is set to true. This is safe because the signatures are checked when the operations are added to the db, and checked again by verifyDb when gatekeeper starts.
A new `perf-test` command was added to the admin CLI:
```
$ ./admin perf-test
getDIDs: 72.517ms
1210 DIDs
resolveDID(did, { confirm: true }): 1.950s
resolveDID(did): 32.385s
resolveDID(did, { verify: true }): 55.424s
```
This change resulted in a ~75% performance gain on average over 1210 DID resolutions. Most DIDs have no updates so are not affected (db access only, or ~30ms per resolution). Some DIDs have many updates and were taking hundreds of ms to resolve.
=> Changed verify semantics in resolveDID

admin-cli.js, gatekeeper-lib.js, gatekeeper.test.js, keymaster.test.js
Extending the work done in #227 
performance test results:
```
$ ./admin perf-test
getDIDs: 121.958ms
1198 DIDs
resolveDID(did, { confirm: true }): 3.197s
resolveDID(did, { confirm: false }): 1.878s
resolveDID(did, { verify: true }): 58.186s
```
16X faster to resolve ~1200 DIDs with the cache compared to before
This also resolves #232
=> Added cache for unconfirmed versions

.github/workflows/docker-publish.yml
Adds the tags from the matrix when pushing to registry
=> fix: docker publish needs a tag

.eslintignore, .eslintrc.json, package-lock.json, package.json
Extends ESlint and includes the react-app for linting.
=> chore: extend eslint for react-app and other policies

src/gatekeeper-lib.js, src/gatekeeper.test.js, src/keymaster-app/src/keymaster-lib.js, src/keymaster-lib.js, src/keymaster.test.js, src/workflow.js
The system should only use confirmed keys for signatures. This is only an issue for the (usually brief) period of time between when an agent rotate keys and when the new keys are confirmed on the registry. During this time the system should use the previous (confirmed) keys for signatures to ensure that all nodes use the same keys for verification.
=> feat: Use only confirmed keys

.github/workflows/docker-publish.yml
Removes CALVER output for Image scanning
=> fix: only run scan for release tag when releasing

.github/workflows/docker-publish.yml
Return exit code 0 if we find critical failures. Temporary bypass.
=> fix: ignore critical errors for now

package.json, src/admin-cli.js, src/gatekeeper-lib.js, src/gatekeeper.test.js, src/keymaster-app/src/keymaster-lib.js
Replaces the two document caches with a single events cache in gatekeeper. An augmented `admin perf-test` measured a 300X performance increase for DID exports (e.g. from 65 seconds to 146ms for 1440 DIDs on one node). This refactor essentially mitigates the load jump seen in #255. 
Even though we are no longer caching documents, and have to reconstruct them from the events cache, no significant change was measured for the resolution benchmarks.
Incidentally it is possible to measure the size of the events cache by noting the number of bytes returned by a call to /export-dids. In this case ~4.6 MB for 1446 DIDs:
```
kc-gatekeeper-1  | POST /api/v1/export-dids 200 90.996 ms - 4585370
```
The response time of 91ms translates to ~63 _microseconds_ per DID.
This PR also adds unit tests for …
=> refactor: Improve db sync performance

dc-tess.yml, docker-compose.yml, src/admin-cli.js, src/config.js, src/gatekeeper-api.js, src/gatekeeper-lib.js, src/gatekeeper.test.js
Supported registries on a per node basis can be specified in a new environment variable:
```
KC_GATEKEEPER_REGISTRIES=hyperswarm,TESS
```
When set as above, the supported list is reflected in the registry dropdown in the web UI:
=> feat: Adds supported registries configuration

src/keymaster-lib.js, src/keymaster.test.js
Now recoverWallet() gracefully handles the case where the wallet was not previously backed up, or if an invalid backup DID is passed in.
=> fix:  Recover wallet

doc/keychain/clients/cli/03-ids.md, doc/keychain/clients/cli/04-dids.md, doc/keychain/clients/cli/05-credentials.md, doc/keychain/clients/cli/06-manifests.md, doc/keychain/clients/cli/07-challenge-responses.md, doc/keychain/clients/cli/08-aliased-names.md, doc/keychain/clients/cli/09-encryption.md, doc/keychain/clients/cli/10-voting.md, doc/keychain/clients/cli/README.md, doc/keychain/clients/webui/02-first-did.md, doc/keychain/clients/webui/03-identities.md, doc/keychain/clients/webui/04-dids.md, doc/keychain/clients/webui/05-groups.md, doc/keychain/clients/webui/06-schema.md, doc/keychain/clients/webui/07-credentials.md, doc/keychain/clients/webui/08-auth.md, doc/keychain/clients/webui/09-wallet.md, doc/keychain/clients/webui/README.md
This adds the frontmatter `experiemental: true` to all docs that don't already have a similar warning. This will display the warning in https://github.com/KeychainMDIP/kc-docs/pull/10 once it is merged.
=> DOC: add experimental warnings

doc/keychain/library/api/index.mdx
Removes the unused ToC block from the API page so that the API plugin can expand right. Also adds the experimental warning to the page.
=> remove ToC block from API page

doc/openapi.json, src/gatekeeper-lib.js, src/kc-app/src/KeymasterUI.js, src/kc-app/src/keymaster-sdk.js, src/keychain-cli.js, src/keymaster-api.js, src/keymaster-app/src/KeymasterUI.js, src/keymaster-app/src/keymaster-lib.js, src/keymaster-lib.js, src/keymaster-sdk.js, src/keymaster.test.js
Adds new function `updateCredential` to keymaster lib, api, and sdk.
In the web wallet, decrypting an issued credential will allow it to be edited. The Update button will enable if the credential is changed (typically the `validFrom`, `validUntil`, and `credential` fields). Once updated, the holder will automatically see the new version. If the holder has published an older version to their manifest, they should unpublish, then publish or reveal again to get the new version.
=> feat: Added updateCredential

doc/openapi.json, packages/gatekeeper/src/gatekeeper-lib.js, packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, scripts/keychain-cli.js, services/gatekeeper/client/src/KeymasterUI.js, services/gatekeeper/server/src/index.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/index.js, services/mediators/hyperswarm/src/index.js, services/mediators/satoshi/src/index.js, tests/gatekeeper.test.js, tests/keymaster.test.js, tests/workflow.js
The response DIDs were not garbage-collected because the validUntil time was stored in the `didDocumentData` which is encrypted for responses.
This fix moves the validUntil time into the mdip section of the DID documents, which makes more sense since the gatekeeper now has responsibility for garbage collection including expired DIDs, and the gatekeeper does not look inside the didDocumentData on principle (so far). As far as the gatekeeper is concerned there are only agents and assets.
Also resolves: Move DID garbage collection into gatekeeper #303 
Also resolves: Use options pattern #338 
The options pattern has a several advantages. By moving optional parameters into a dictionary, it makes the code more readable with named parameters, e.g.
```
const ok = await …
```
=> fix: response DIDs should be ephemeral

packages/gatekeeper/README.md, packages/gatekeeper/src/gatekeeper-lib.js, packages/gatekeeper/src/gatekeeper-sdk.js, packages/keymaster/README.md, packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, sample.env, scripts/admin-cli.js, scripts/keychain-cli.js, services/gatekeeper/client/src/App.js, services/gatekeeper/server/src/gatekeeper-api.js, services/keymaster/server/src/keymaster-api.js, services/mediators/hyperswarm/src/hyperswarm-mediator.js, services/mediators/satoshi/src/satoshi-mediator.js, tests/gatekeeper.test.js, tests/keymaster.test.js, tests/workflow.js
All start functions (gatekeeper and keymaster, lib and sdk) now take single options parameter. The setURL and and waitForReady functions for the sdks have been rolled into the start function, and are therefore deprecated.
The READMEs have been updated with examples:
gatekeeper
```
// Try connecting to the gatekeeper service every second,
// and start reporting (chatty) if not connected after 5 attempts
await gatekeeper.start({
url: 'http://gatekeeper-host:4224',
waitUntilReady: true,
intervalSeconds: 1,
chatty: false,
becomeChattyAfter: 5
});
```
keymaster
```
await gatekeeper_sdk.start({
url: 'http://gatekeeper-host:4224',
waitUntilReady: true,
intervalSeconds: 5,
chatty: true
});
await keymaster_lib.start({
gatekeeper: gatekeeper_sdk,
wallet: browser_wallet,
cipher: cipher_web
});
```
=> refactor: Simplify start functions

README.md, doc/openapi.json, packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, scripts/keychain-cli.js, scripts/swagger.sh, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster.test.js
Adds new API endpoints:
- `GET /groups`
- `GET /schemas`
Removes deprecated endpoint:
- `POST /credentials/new`
Renames all `/poll/` endpoints to `/polls/`
Changes all endpoints to return JSON with named return values.
Adds new CLI commands:
- `get-asset`
- `list-groups`
- `get-group`
- `list-schemas`
- `get-schema`
- `list-credentials`
- `get-credential`
Changed all commands to follow `verb-subject` pattern which mostly affected the group commands:
- `group-create` -> `create-group`
- `group-add` -> `add-group-member`
- `group-remove` -> `remove-group-member`
- `group-test` -> `test-group`
The associated keymaster lib function names were changed to follow suit.
Also fixed an issue with reveal credential in the web wallet and CLI.
Also adds a script to start a swagger editor in a docker …
=> refactor: improve consistency of Keymaster API

packages/gatekeeper/src/gatekeeper-lib.js, scripts/admin-cli.js, services/gatekeeper/server/src/gatekeeper-api.js, services/mediators/hyperswarm/src/hyperswarm-mediator.js, services/mediators/satoshi/src/satoshi-mediator.js, tests/gatekeeper.test.js
Removed import loop from gatekeeper-api, clients are responsible for invoking processEvents when they are finished importing event batches.
Removed batch tracking from hyperswarm-mediator, the gatekeeper-api is now responsible for tracking which events have already been seen so they can be discarded from the import queue.
Also, satoshi-mediator no longer reports an error if a batch DID discovered on the blockchain can't be resolved yet.
=> refactor: processEvents

docker-compose.yml, packages/gatekeeper/src/gatekeeper-lib.js, services/mediators/satoshi/src/satoshi-mediator.js, tests/gatekeeper.test.js
Original intent was to improve the information the satoshi-mediator saves to track importing batches of operations from the blockchain. A typical entry now includes separate properties `imported` and `processed` to record the responses to `importBatch` and `processEvents` respectively:
```
{
"height": 89080,
"index": 1,
"time": "2024-10-17T14:03:03.000Z",
"txid": "153a0f3810d1ed026ee2cbfe3eb58be9e73ec481ec952870186efa9a5d27664a",
"did": "did:test:z3v8AuaeY7Lammz8Xm1iQqt4Uz2ScCVHsTWZ8FEVuBVHtFMKbEZ",
"imported": {
"queued": 1,
"processed": 0,
"rejected": 0,
"total": 1
},
"processed": {
"added": 0,
"merged": 1,
"pending": 0
}
}
```
Two related issues were discovered and fixed:
- gatekeeper was removing events from its processing queue at the completion of processEvents under the mistaken …
=> fix: Improve batch import tracking

package-lock.json, packages/keymaster/package.json, packages/keymaster/src/keymaster-lib.js, tests/keymaster.test.js
Replaces the json-schema-faker package dependency with a simple utility function `generateSchema` that works only with simple schemas (list of named properties).
Also improves `bindCredential` to use a default credential if specified in options rather than generating a default from the schema.
=> refactor: Replaced json-schema-faker dependency

packages/keymaster/src/keymaster-lib.js, services/mediators/hyperswarm/src/hyperswarm-mediator.js, tests/keymaster.test.js
Moves group properties under a `group` label in the `didDocumentData`
Backwards compatible with existing group DIDs which will be automatically upgraded if they are updated.
=> refactor: Upgrade groups

packages/keymaster/src/keymaster-lib.js, tests/keymaster.test.js
Moves poll properties under a `poll` label in the `didDocumentData`
Backwards compatible with existing poll DIDs which will be automatically upgraded if they are updated.
=> refactor: Upgrade polls

services/mediators/satoshi/src/satoshi-mediator.js
Improves the resilience of satoshi-mediator on startup. After connecting to the blockchain node the mediator will create the wallet if it doesn't already exist (fixes #312). If the mediator can't create or access the wallet it will exit immediately.
Then the mediator will either create the NodeID (agent) if it doesn't exist, or wait for gatekeeper to sync until the NodeID is resolveable (in case the gatekeeper is resyncing from an empty db).
=> fix: satoshi-mediator startup improvements

packages/keymaster/src/keymaster-lib.js, python/keymaster_sdk.py, python/test.py, tests/keymaster.test.js
Changes the semantics of issueCredential so that it properly handles unbound credentials if (and only if) the credential's schema and subject are specified in the options, like so:
```
const subject = await keymaster.createId('Bob');
const schema = await keymaster.createSchema(mockSchema);
const unboundCredential = await keymaster.createTemplate(schema);
const did = await keymaster.issueCredential(unboundCredential, { subject, schema });
```
Note that the signature of issueCredential (and the corresponding endpoint in the API) are unchanged.
=> refactor: issueCredential

services/mediators/hyperswarm/src/hyperswarm-mediator.js
The hyperswarm-mediator (once again) tracks the batches that it receives from other nodes via `batch` and `queue` messages, and discards the ones that it has seen before. This doesn't prevent gossip storms caused by nodes running older versions, but new nodes will not make the problem worse. Once all nodes are upgraded, the problem should be mitigated.
=> fix: Prevent hyperswarm gossip storm

docker-compose.yml
Points to Keychainmdip dockerhub for bitcoin-core docker image.
=> chore: point to dockerhub for bitcoin-core

doc/mdip/scheme.md, packages/gatekeeper/src/db-json-cache.js, packages/gatekeeper/src/gatekeeper-lib.js, packages/keymaster/src/keymaster-lib.js, tests/gatekeeper.test.js
Adds a `previd` property to all update and delete operations that references the CID of the latest version's operation (replacing the unused `prev` property). This new property is used to verify that the operation is applied to specified version.
The operation cid is also included as `mdip.opid` in every resolved DID.
Also includes a fix for an issued discovered during testing in getEvents() in db-json-cache. The fix ensures a copy of the events is returned instead of a mutable reference.
=> feat: Re-enable hash check on operations

docker-compose.yml, packages/keymaster/src/db-wallet-json-enc.js, packages/keymaster/src/db-wallet-json.js, scripts/keychain-cli.js, services/keymaster/server/src/config.js, services/keymaster/server/src/keymaster-api.js, services/mediators/satoshi/src/config.js, services/mediators/satoshi/src/satoshi-mediator.js, tests/keymaster.test.js
Adds encrypted wallet support to keymaster-api and satoshi-mediator. Also changes the CLI `encrypt-wallet` command to encrypt the wallet in-place (same file).
Procedure to switch to encrypted server wallet:
1. `./stop-node` 
1. `cp data/wallet.json ~` to backup the current wallet file to your home directory
1. Add `KC_ENCRYPTED_PASSPHRASE="your secret passphrase"` to your .env file
1. `./start-node gatekeeper` to start just the gatekeeper service
1. `./kc encrypt-wallet` (should return OK)
1. `./stop-node`
1. `./start-node gatekeeper keymaster` and check keymaster log for errors
1. `./stop-node`
1. `./start-node`
Procedure to switch back to unencrypted wallet:
1. `./kc show-wallet > unencrypted.json`
1. `./stop-node`
1. Set `KC_ENCRYPTED_PASSPHRASE=""` in your .env file
1. `mv …
=> feat: Added encrypted wallet support to services

services/keymaster/server/src/keymaster-api.js, services/mediators/satoshi/src/satoshi-mediator.js
Call to setWallet() when using encryption is missing on the API and Satoshi mediator.
=> fix: update api and mediator to set wallet when using encryption

packages/keymaster/src/keymaster-lib.js, scripts/keychain-cli.js, services/mediators/hyperswarm/src/hyperswarm-mediator.js, tests/hypr-confirm.js, tests/keymaster.test.js
One-line fix in hyperswarm-mediator changing an `importBatch` to a `mergeBatch` so that events are processed immediately after the import which fixes the confirmation delay on hyperswarm.
The rest of the PR fixes an issue discovered during testing with the `create-challenge` CLI command which was failing on an empty challenge.
=> fix: Confirmation delay on hyperswarm registry

packages/gatekeeper/src/gatekeeper-lib.js, packages/gatekeeper/src/gatekeeper-sdk.js, scripts/admin-cli.js, services/gatekeeper/server/src/gatekeeper-api.js, tests/gatekeeper.test.js
Adds `GET /status` to the gatekeeper endpoints. The command `./admin get-status` can be used to see the results:
```bash
$ ./admin get-status
{
"uptimeSeconds": 1165,
"dids": {
"total": 10545,
"ephemeral": 3,
"invalid": 0,
"byRegistry": {
"TFTC": 3106,
"hyperswarm": 1719,
"TBTC": 3117,
"TESS": 2579,
"local": 24
}
},
"memoryUsage": {
"rss": 220835840,
"heapTotal": 78938112,
"heapUsed": 44739752,
"external": 23612780,
"arrayBuffers": 21134862
}
}
```
gatekeeper will log the status every minute:
```
gatekeeper-1  | Status -----------------------------
gatekeeper-1  | DID Database:
gatekeeper-1  |   Total: 10545
gatekeeper-1  |   By registry:
gatekeeper-1  |     TFTC: 3106
gatekeeper-1  |     hyperswarm: 1719
gatekeeper-1  |     TBTC: 3117
gatekeeper-1  |     TESS: 2579
gatekeeper-1  | …
```
=> feat: Added gatekeeper status

packages/gatekeeper/src/gatekeeper-lib.js, services/gatekeeper/server/src/gatekeeper-api.js, tests/gatekeeper.test.js
Added the db type and confirmed count and DIDs by version to the status report:
```
gatekeeper-1  | Status -----------------------------
gatekeeper-1  | DID Database (redis):
gatekeeper-1  |   Total: 10600
gatekeeper-1  |   By registry:
gatekeeper-1  |     TBTC: 3117
gatekeeper-1  |     TESS: 2579
gatekeeper-1  |     TFTC: 3150
gatekeeper-1  |     hyperswarm: 1730
gatekeeper-1  |     local: 24
gatekeeper-1  |   By version:
gatekeeper-1  |     1: 9448
gatekeeper-1  |     2: 679
gatekeeper-1  |     3: 292
gatekeeper-1  |     4: 52
gatekeeper-1  |     5: 32
gatekeeper-1  |     6+: 97
gatekeeper-1  |   Confirmed: 10020
gatekeeper-1  |   Ephemeral: 2
gatekeeper-1  |   Invalid: 0
gatekeeper-1  | Memory Usage Report:
gatekeeper-1  |   RSS: 208.11 MB (Resident Set Size - total memory allocated …
```
=> feat: Added db and versions to status

packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, scripts/keychain-cli.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster.test.js
Fixes `issueCredential()` so that it no longer adds ephemeral DIDs to the wallet.
Also adds `listAssets()` to keymaster lib and sdk, `GET /assets` to the api, and `list-assets` to the CLI.
=> fix: Don't add ephemeral DIDs to wallet

packages/gatekeeper/src/config.js, packages/gatekeeper/src/gatekeeper.js, tests/gatekeeper.test.js
Also adds `canonicalId` to didDocumentMetadata as per [W3C recommendation](https://www.w3.org/TR/did-core/#did-document-metadata) which can have a different prefix than the requested DID.
=> refactor: Default DID prefix configuration

packages/gatekeeper/src/gatekeeper-client.js, packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, python/keymaster_sdk/src/keymaster_sdk/keymaster_sdk.py, scripts/keychain-cli.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster.test.js
Removes `resolveId` method from keymaster interface. Use `resolveDID` instead since it is equivalent.
Adds `getName` to keymaster interface which returns the DID associated with the given name.
CHANGES `GET /names/:name` endpoint in API. Maps to `getName` rather than `resolveDID`
ADDS `GET /did/:id` endpoint to API. Resolves an identifier (id can be a name or a DID)
=> refactor: keymaster API

browser/chrome-extension/src/offscreen/offscreen.ts, browser/chrome-extension/src/popup/PopupContext.tsx, browser/chrome-extension/src/wallet/WalletUI.tsx
Use the newly added offscreen HTML to store the browser extension state in memory and not store the state to disk.
Resolves: https://github.com/KeychainMDIP/kc/issues/550
=> Store extension state in memory

browser/chrome-extension/src/viewer/JsonViewer.tsx, browser/chrome-extension/src/wallet/WalletUI.tsx
In the Chrome browser extension data is truncated, this PR disables truncation.
Resolves: https://github.com/KeychainMDIP/kc/issues/557
=> fix: extension prevent truncation on JSON viewer

packages/keymaster/src/keymaster-lib.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster.test.js
Fixes an issue in Keymaster service that was causing the recoverId feature to fail.
Also now throws an error if the recovered ID already exists in the wallet, preventing accidental overwriting.
=> fix: Recover ID for server wallet

README.md, doc/keychain/clients/cli/03-ids.md, doc/keychain/clients/cli/README.md, packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, python/keymaster_sdk/src/keymaster_sdk/keymaster_sdk.py, scripts/keychain-cli.js, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster.test.js
Adds the renameId() function to Keymaster lib and KeymasterClient sdk. Also adds corresponding `POST /ids/:id/rename` endpoint to the API, and `rename-id` command to the CLI.
Added bonus: ID names support Unicode...
=> feat: Added renameId

README.md, doc/keychain/clients/cli/README.md, packages/keymaster/src/keymaster-lib.js, packages/keymaster/src/keymaster-sdk.js, scripts/keychain-cli.js, services/keymaster/server/src/keymaster-api.js, tests/keymaster-client.test.js, tests/keymaster.test.js
Adds `PUT /assets/:id` to the keymaster REST API, and the corresponding updateAsset() function in KeymasterClient. 
CLI changes
`create-asset` - The file is now optional. If missing, an empty asset is created.
`set-asset` - New command to set the data of an asset. If file is missing, data will be reset to empty.
`set-property` - New command to set a single key-value pair in an asset's data. If value is missing the key will be removed.
Also fixes an issue that allows allows keymasters to sign operations even if the connected gatekeeper changes its default DID prefix.
=> feat: Added updateAsset to keymaster API

packages/gatekeeper/src/gatekeeper.js, tests/gatekeeper.test.js
Gatekeeper internal importEvent now properly handles DID operation reorg events (described in #478). This is essential for solving the double-spend problem.
=> refactor: importEvent

packages/gatekeeper/src/db/json.js, packages/gatekeeper/src/db/mongo.js, packages/gatekeeper/src/db/redis.js, packages/gatekeeper/src/db/sqlite.js, packages/gatekeeper/src/gatekeeper.js, tests/gatekeeper.test.js
New option `maxQueueSize` added to Gatekeeper to limit the number of events in a registry queue. If a mediator stops draining its queue for whatever reason, and the queue fills up, the associated registry will be removed from the supported registry list until the mediator starts up again. While the registry is removed, createDID and updateDID will return an InvalidOperation error.
The monodb and sqlite db adapters were fixed to clear all queues in resetDb.
Also resolves #607
=> fix: Add registry queue size limit

package-lock.json, packages/cipher/package.json, packages/common/package.json, packages/gatekeeper/package.json, packages/ipfs/package.json, packages/keymaster/package.json, sample.env, services/mediators/hyperswarm/src/config.js
Updated package versions to `1.0.0`
Updated default hyperswarm network `KC_MDIP_PROTOCOL=/MDIP/v1.0-public`
=> chore: Prepare v1.0 release

.github/workflows/swagger-jsdoc.yml
- In the JSDoc workflow if there is nothing to commit then do not return an error.
=> fix: JSDoc workflow ignore empty commit

.github/workflows/swagger-jsdoc.yml
- Fixes an issue where git in the swagger workflow running on a tag throws an error due to the being in a detached state.
=> fix: swagger workflow should use main branch

browser/chrome-extension/src/browser/BrowserContent.tsx, browser/chrome-extension/src/browser/browser.tsx, browser/chrome-extension/src/browser/components/CredentialsTab.tsx, browser/chrome-extension/src/browser/components/GroupsTab.tsx, browser/chrome-extension/src/browser/components/IssueTab.tsx, browser/chrome-extension/src/browser/components/IssuedTab.tsx, browser/chrome-extension/src/browser/components/JsonViewer.tsx, browser/chrome-extension/src/browser/components/SchemaTab.tsx, browser/chrome-extension/src/browser/components/WalletTab.tsx, browser/chrome-extension/src/popup/PopupContent.tsx, browser/chrome-extension/src/popup/components/AuthTab.tsx, browser/chrome-extension/src/popup/components/DIDsTab.tsx, browser/chrome-extension/src/shared/DisplayDID.tsx, browser/chrome-extension/src/shared/DropDownID.tsx, browser/chrome-extension/src/shared/HeldTab.tsx, browser/chrome-extension/src/shared/IdentitiesTab.tsx, browser/chrome-extension/src/shared/TextInputModal.tsx, browser/chrome-extension/src/shared/WarningModal.tsx, browser/chrome-extension/src/shared/contexts/ContextProviders.tsx, browser/chrome-extension/src/shared/contexts/UIContext.tsx, browser/chrome-extension/src/shared/contexts/WalletProvider.tsx, packages/keymaster/types/index.d.ts
- Resolves https://github.com/KeychainMDIP/kc/issues/610
- When MDIP browser is open popup menu items, issued button and issue button no longer open new tabs but navigate the open tab.
- Introduce DisplayDID component to show a DID with copy button, DID will truncate, tooltip shows full DID. Used in groups, issued and issue tabs.
=> feat: complete identity tab in Chrome browser extension

docker-compose.yml, sample.env
Also now uses `KC_GATEKEEPER_PORT` and `KC_KEYMASTER_PORT` to make it easier to run multiple nodes on the same machine, simply make sure each node uses a different port e.g. 14224, 24224, 34224 to run 3 gatekeepers on the same machine.
=> fix: Default registry in docker file

scripts/keychain-cli.js
Now duplicate names will get a proper error message:
```
./kc add-name test did:test:z3v8AuaTvSWN6rpc9ZtRigpnGduhBsUmYmAWC2kRt6QHeE8FaHK
Error: Invalid parameter: name already used
```
=> fix: Fixed calls to addName in kc CLI

packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, tests/keymaster-client.test.ts
This PR fixes the backup-id CLI command by refining the parameter handling and backup process.
-    Renames the parameter in backupId to improve clarity
-    Updates the backup process by fetching ID info based on either the provided value or the current wallet state
-    Adds a fallback in the client implementation to retrieve the current ID when none is provided
=> fix: backup-id CLI command

doc/keymaster-api.json, packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, scripts/keychain-cli.js, services/keymaster/server/src/keymaster-api.ts, tests/keymaster-client.test.ts, tests/keymaster.test.ts
This pull request introduces a new "clone-asset" feature that allows users to clone existing assets in the system. Key changes include:
-    Addition of new tests for cloneAsset functionality in both keymaster and keymaster-client test files.
-    Implementation of the cloneAsset API endpoint and corresponding service logic in Keymaster and KeymasterClient.
-    Integration of new CLI commands to access both cloneAsset and transferAsset functionalities.
=> feat: Adds clone-asset command

doc/keymaster-api.json, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, scripts/keychain-cli.js, services/keymaster/server/src/keymaster-api.ts, tests/keymaster.test.ts
Refactored createAsset method so that names can be validated (if provided) before assets are created. If a valid name is provided, the new asset will be added to the wallet names list.
=> feat: Added name to createAsset options

services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
This PR adds a new feature to allow cloning of assets, and refactors the registry selection UI by extracting it into a reusable component. Key changes include:
-    Introducing the cloneAsset function that handles asset cloning with error notifications.
-    Extracting inline registry selection into a new RegistrySelect component and replacing duplicate code segments.
-    Updating both the keymaster and gatekeeper clients to leverage these new changes.
=> feat: Adds clone asset to web wallet

packages/keymaster/src/keymaster.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, tests/keymaster.test.ts
Changed web wallet to disable edit buttons for assets that are not owned by the user.
To enable this, the Keymaster.resolveAsset() method was changed to include a new flag `isOwned` in the return data that checks if the asset's controller is one of the IDs in the wallet.
=> feat: Web wallet checks ownership of asset before updating

packages/keymaster/src/keymaster.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/mediators/hyperswarm/src/hyperswarm-mediator.ts, tests/keymaster.test.ts
This PR enables the web wallet to transfer assets by updating the asset resolution logic, modifying test expectations to remove the isOwned field, and adding a transfer workflow in the UI.
-    Replaces resolveAsset calls with resolveDID to align with the updated ownership model
-    Updates tests and UI functions to remove isOwned augmentation from resolved documents
-    Introduces a new transferName function for asset transfers in the UI
Also refactors keymaster updateDID method to return immediately if no changes to the DID document are detected.
=> feat: Enables web wallet to transfer asset

docker-compose.yml, services/keymaster/server/src/config.js, services/keymaster/server/src/keymaster-api.ts, services/mediators/hyperswarm/src/hyperswarm-mediator.ts
This PR fixes issues with the Keymaster service by ensuring that the node ID is properly resolved before proceeding. Key changes include:
-    Updating the peer addition logic in hyperswarm-mediator to validate structure before using the resolved data.
-    Renaming and updating the waiting function in keymaster-api to use config.nodeID for resolution.
-    Introducing a new configuration property (nodeID) and propagating it to docker-compose.
=> fix: Keymaster waits for node ID to resolve

packages/keymaster/src/keymaster.ts, tests/keymaster.test.ts
This PR updates the updateAsset functionality to merge new data into the existing asset data rather than replacing it entirely.
-    Adds tests to verify the merging behavior and removal of properties when updated to undefined.
-    Modifies the updateAsset implementation to merge existing data with new changes.
=> feat: Changed updateAsset to merge data

README.md, browser/chrome-extension/src/browser/components/ImageTab.tsx, doc/keychain/clients/cli/README.md, doc/keymaster-api.json, packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, scripts/keychain-cli.js, services/keymaster/server/src/keymaster-api.ts, tests/cli-tests/test_cli_validate_help.expect, tests/keymaster-client.test.ts, tests/keymaster.test.ts
This PR adds support for document assets in keymaster by implementing new endpoints, client methods, and tests while updating related types and CLI commands.
-    Added tests for document creation, update, retrieval, and validation.
-    Implemented new document asset endpoints in the server API with Swagger documentation.
-    Updated client, CLI scripts, and types to support document asset operations.
=> feat: Adds document assets to keymaster

.github/workflows/docker-build-test.yml, tests/cli-tests/README.md, tests/cli-tests/generate_test_env.sh, tests/cli-tests/test_cli_add_name.expect, tests/cli-tests/test_cli_backup_id.expect, tests/cli-tests/test_cli_check_list_ids.expect, tests/cli-tests/test_cli_check_wallet.expect, tests/cli-tests/test_cli_create_id.expect, tests/cli-tests/test_cli_create_schema.expect, tests/cli-tests/test_cli_create_schema_template.expect, tests/cli-tests/test_cli_create_wallet.expect, tests/cli-tests/test_cli_encrypt_file.expect, tests/cli-tests/test_cli_get_credential_by_id.expect, tests/cli-tests/test_cli_get_schema.expect, tests/cli-tests/test_cli_import_wallet.expect, tests/cli-tests/test_cli_issue_credential.expect, tests/cli-tests/test_cli_list_credentials.expect, tests/cli-tests/test_cli_list_dids.expect, tests/cli-tests/test_cli_list_issue_credentials.expect, tests/cli-tests/test_cli_list_names.expect, tests/cli-tests/test_cli_list_schema.expect, tests/cli-tests/test_cli_remove_id.expect, tests/cli-tests/test_cli_remove_name.expect, tests/cli-tests/test_cli_resolve_id.expect, tests/cli-tests/test_cli_reveal_credentials.expect, tests/cli-tests/test_cli_revoke_credentials.expect, tests/cli-tests/test_cli_rotate_keys.expect, tests/cli-tests/test_cli_show_mnemonic.expect, tests/cli-tests/test_cli_show_wallet.expect, tests/run_cli_tests.sh
This activates a new pipeline for running the CLI tests. I have ran these tests locally passing the new flag. I updated the README. There might still need to be changes for this to work. But I was able to confirm using a local service that replicates "GitHub runners" and was able to see it pass. 
This doesnt impact existing workflows for now. When we know it is working we can consolidate and or replace existing ones.
=> test: setup pipeline for cli tests

README.md, doc/keychain/clients/cli/README.md, scripts/keychain-cli.js
This PR updates the CLI commands to replace optional positional parameters with explicit options for registry and DID name handling.
-    Modified the "create-id" command to remove the positional [registry] parameter and add the "--registry" option.
-    Revised the "issue-credential" command to remove the positional [registry] and [name] parameters and instead add "--registry" and "--name" options.
=> fix: Updated issue-credential command options

packages/keymaster/src/keymaster.ts, scripts/keychain-cli.js, tests/keymaster.test.ts
This PR fixes the behavior of createGroup so that the group name and the DID name are clearly distinguished across tests, CLI, and the keymaster module.
-    Updated test cases to reflect the new behavior, avoiding member assignment and resolving by group name
-    Modified CLI command and keymaster.ts createGroup to align with the new naming distinction
=> fix: Distinguish group name and DID name in createGroup

.github/workflows/release-publish.yml
Resolves #793. 
This will trigger when a new tag is create in the repo either by push to the repo or when a GH Release is Approved which generates a new tag. This will only trigger for the tag format of : "v*"
=> ci: add new pipeline for releases after tags been created

README.md, doc/gatekeeper-api.json, doc/mdip/scheme.md, docker-compose.yml, packages/gatekeeper/src/db/abstract-json.ts, packages/gatekeeper/src/db/mongo.ts, packages/gatekeeper/src/db/redis.ts, packages/gatekeeper/src/db/sqlite.ts, packages/gatekeeper/src/gatekeeper-client.ts, packages/gatekeeper/src/gatekeeper.ts, packages/gatekeeper/src/types.ts, packages/keymaster/src/keymaster.ts, scripts/admin-cli.js, services/gatekeeper/server/src/gatekeeper-api.ts, services/mediators/satoshi/src/satoshi-mediator.ts, tests/gatekeeper-client.test.ts, tests/gatekeeper.test.ts
Resolves #683 
This PR adds timestamp support to DID metadata by tracking block information throughout the system. Key changes include:
-    Adding block info (blockid, height, time, etc.) to operations in Gatekeeper and Keymaster modules.
-    Introducing new endpoints, CLI commands, and tests to handle block addition and retrieval.
-    Updating database adapters (SQLite, Redis, Mongo, and JSON) to store and retrieve block information.
=> feat: Adds timestamps to DID metadata

.github/workflows/docker-build.yml, .github/workflows/docker-publish.yml, .github/workflows/release-publish.yml
This PR adds support for building and publishing two new services—explorer and search-server—in the CI workflows.
-    Updates the release publish workflow to include explorer and search-server docker images.
-    Updates the docker publish workflow to add corresponding pre-release tags for explorer and search-server.
-    Updates the docker build workflow with build instructions for explorer and search-server.
=> ci: Added explorer to docker workflow

.github/workflows/build-chrome-extension.yml, .github/workflows/build-explorer.yml, .github/workflows/swagger-jsdoc.yml, Dockerfile.cli, Dockerfile.explorer, Dockerfile.gatekeeper, Dockerfile.hyperswarm, Dockerfile.keymaster, Dockerfile.satoshi, Dockerfile.search-server, README.md
[node:18.20.8-bullseye-slim](https://hub.docker.com/layers/library/node/18.20.8-bullseye-slim/images/sha256-cf2eabd2977de67144469693e99714631fceb1e7456a6843571b6d78bc824414) has the fewest vulnerabilities for a node v18 base image
=> fix: Upgrade node to v18.20.8

.github/workflows/docker-build-test.yml
Activates the testing pipeline for CLI tests. After this is merged we can add a rule to enforce it must pass before merging.
=> ci: update workflow to trigger on PRs

.github/workflows/build-chrome-extension.yml, .github/workflows/build-explorer.yml, .github/workflows/swagger-jsdoc.yml, .github/workflows/unit-test.yml, Dockerfile.cli, Dockerfile.explorer, Dockerfile.gatekeeper, Dockerfile.hyperswarm, Dockerfile.keymaster, Dockerfile.satoshi, Dockerfile.search-server, README.md, package-lock.json, packages/cipher/src/cipher-node.ts, packages/gatekeeper/package.json, packages/gatekeeper/src/db/json-memory.ts, packages/gatekeeper/src/gatekeeper.ts, packages/ipfs/package.json, packages/keymaster/package.json, packages/keymaster/src/db/json-memory.ts, tests/gatekeeper.test.ts, tests/keymaster.test.ts
This PR upgrades the Node.js version to v22.15.0 LTS and updates related dependency versions and configurations.
-    Added a new in-memory JSON storage implementation for keymaster and gatekeeper (replacing mockFs in the unit tests)
-    Upgraded dependencies and updated Node.js versions in Dockerfiles, GitHub workflows, and documentation.
=> refactor: Upgrade node to v22.15.0 LTS

packages/keymaster/src/keymaster.ts, tests/keymaster.test.ts
This PR adds validation for GroupVault item names to reject empty or whitespace-only names and expands tests accordingly.
-    Integrated validateName call in addGroupVaultItem to enforce non-empty item names.
-    Enhanced test suite with cases for unicode names and various invalid name inputs.
=> feat: Validate GroupVault item names

packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, scripts/keychain-cli.js, tests/keymaster.test.ts
This PR introduces a new GroupVault option for secret members (meaning vault members cannot view other members), adds corresponding tests and updates to CLI and internal types and logic in Keymaster.
-    Added new tests for GroupVault member operations and error cases
-    Updated CLI options for creating a group vault with secret members
-    Modified GroupVault creation, decryption, and owner checking logic in the Keymaster implementation
=> feat: Adds GroupVault option for secret members

services/mediators/hyperswarm/src/hyperswarm-mediator.ts
This PR aims to fix issues related to tracking bad IPFS peers by recording the first failure timestamp. Key changes include:
-    Introducing a new badPeers record to track IPFS peer errors.
-    Updating log messages for added and error cases to indicate "IPFS peer".
-    Adding error handling logic to prevent duplicate logging when a peer fails repeatedly.
=> fix: Track bad IPFS peers

docker-compose.yml, package-lock.json, packages/keymaster/package.json, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, tests/keymaster.test.ts
Adds first‐class support for storing and retrieving login credentials in group vaults, including core type updates, tests, and UI enhancements.
-    Define a new GroupVaultLogin type and detect MIME types in addGroupVaultItem
-    Add tests covering adding and retrieving JSON‐encoded login items
-    Enhance the Keymaster UI to add, display, and reveal login entries with dialogs and icons
=> feat: Add shared logins to group vaults

packages/cipher/src/cipher-node.ts, packages/cipher/src/cipher-web.ts, packages/cipher/src/types.ts, tests/cipher.test.ts, tests/gatekeeper.test.ts
This PR adds proof-of-work support to both web and node Cipher implementations, updates types, and adds related tests.
-    Introduces a ProofOfWork interface 
-    Implements hasLeadingZeroBits, addProofOfWork, and checkProofOfWork in both CipherWeb and CipherNode.
-    Adds comprehensive unit tests for PoW functionality in cipher.test.ts.
-    Cleans up gatekeeper.test.ts by removing redundant empty beforeEach hooks.
=> feat: Adds PoW primitives to Cipher classes

doc/keymaster-api.json, packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, services/keymaster/server/src/keymaster-api.ts, tests/keymaster/client.test.ts, tests/keymaster/dmail.test.ts, tests/keymaster/notice.test.ts
This PR introduces the concept of “notices” alongside existing Dmail workflows, implementing creation, verification, updating, importing, and refreshing of notice assets in both the core library and HTTP API, and adds corresponding tests.
-    Define NoticeMessage type and core methods (verifyNotice, createNotice, updateNotice, importNotice, refreshNotices) in Keymaster.
-    Extend HTTP routes (/notices, /notices/{id}, /notices/refresh) and client to support notice operations.
-    Add end-to-end tests for notice behavior and update Dmail tests to expect notice DIDs.
=> feat: Adds notice asset type

start-node-ci
GH updated the docker and docker compose versions they are using. There's a regression or unexpected change where if we call "docker compose up cli" It should build and run the service and its dependencies to run. 
For some reason that now has broken in the new version.
The fix is to "explicitly" call each service to build and run in the command so it can build locally and run it.
=> ci: update cli test script to build each service it needs vs only dependencies

packages/keymaster/src/keymaster.ts, tests/keymaster/group-vault.test.ts
This PR implements a feature in GroupVaults to store copies of small items within the DID docs. Key changes include:
-    Adding tests to verify that large BLOBs are handled separately and small items are stored inline.
-    Introducing a new property (maxDataLength) in the Keymaster class to determine when to store data inline.
-    Updating logic in Keymaster to conditionally include inline data for items below the size threshold.
=> feat: Adds local storage for GroupVaults

packages/keymaster/src/keymaster.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, tests/keymaster/notice.test.ts
This PR adds support for a cc list in dmail functionality while updating corresponding UI handling and backend notice cleanup tests.
-    Modified test descriptions and added a new test for handling expired notices.
-    Refactored dmail recipient handling in the UI to support multiple "To" and "Cc" recipients.
-    Updated notice removal logic in the backend to reflect refined conditions for revoked versus expired notices.
=> feat: Adds cc list to dmail

.github/workflows/e2e-test-report.yml
Just updates the artifact name to use the artifact name vs the folder name in the project
=> ci: use artifact name from previous run vs actual folder name

doc/keymaster-api.json, packages/keymaster/src/keymaster-client.ts, packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, services/keymaster/server/src/keymaster-api.ts, tests/keymaster/client.test.ts, tests/keymaster/dmail.test.ts
This PR adds full support for Dmail attachments across the stack, including tests, API endpoints, client implementations, and UI integration.
-    Introduces new server routes and client methods to list, add, remove, and retrieve attachments.
-    Extends the Keymaster core and client packages with attachment operations.
-    Updates tests and the React UI to cover and display Dmail attachments.
=> feat: Adds dmail attachments

packages/keymaster/src/keymaster.ts, packages/keymaster/src/types.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
Implements Dmail revocation controls in the UI and extends the Keymaster API with new Dmail attachment methods.
-    UI: Clears the “To” field on reset, adds Edit and Revoke Dmail buttons, and implements a revokeDmail handler.
-    API: Adds fileDmail and attachment-related signatures in KeymasterInterface, and implements add/remove/get attachment in the Keymaster class.
=> feat: Adds dmail revocation

packages/keymaster/src/keymaster.ts, services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js, tests/keymaster/dmail.test.ts
Adds the ability to mark dmails as read or unread by introducing a new UNREAD tag, updating backend defaults, adjusting tests, and extending the UI with toggle buttons and styling for unread items.
-    Introduce DmailTags.UNREAD in both client and package enums
-    Default new/incoming dmails to include the UNREAD tag
-    Update tests to expect the new tag and extend UI with mark-as-read/unread controls
=> feat: Adds ability to mark dmails as read or unread

services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
Adds interactive sorting for dmail tables in both Keymaster and Gatekeeper UIs
-    Introduces dmailSortBy and dmailSortOrder state hooks
-    Implements sortedDmailEntries via useMemo with a comparator for sender, subject, and date
-    Updates table headers to use TableSortLabel for clickable, visual sort controls
=> feat: Adds dmail sorting

services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
This PR adds the ability to forward attachments when forwarding a dmail
-    Adds dmailForwarding state and populates it when forwarding a message
-    Implements copying of attachments in createDmail if dmailForwarding is set
-    Adds a “Clear Dmail” button in the send UI and calls clearSendDmail after refresh
-    Refactors the compare function to use direct array indexing instead of unused variables
=> fix: Adds dmail attachment forwarding

services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
This PR adds ephemeral dmail functionality that allows users to create time-limited emails that automatically expire. The feature is specifically implemented for the hyperswarm registry with validation to ensure proper date handling and user experience.
Key changes:
-    Added ephemeral dmail toggle and expiration date selection in the UI
-    Implemented validation logic for ephemeral dmail creation with future date requirements
-    Enhanced the dmail creation process to support time-limited messages
=> feat: Adds ephemeral dmail

services/gatekeeper/client/src/KeymasterUI.js, services/keymaster/client/src/KeymasterUI.js
This PR adds functionality to allow users to add dmail senders as contacts directly from the dmail interface. The feature provides a convenient way to quickly add contacts from received messages.
-    Added a new addDmailContact function that sets up a sender's DID as a contact and navigates to the names tab
-    Added a "PersonAdd" icon button next to sender information in the dmail view
-    The contact addition is only shown for senders with DID identifiers
=> feat: Add dmail contact to names

docker-compose.yml, packages/gatekeeper/src/gatekeeper-client.ts, tests/gatekeeper/client.test.ts
This PR adds functionality to the GatekeeperClient to manage custom HTTP headers, allowing users to add and remove headers that will be included in all requests made by the client.
-    Adds addCustomHeader and removeCustomHeader methods to the GatekeeperClient class
-    Includes comprehensive test coverage for the new header management functionality
-    Also shortens docker-compose service name for the signet inscription mediator
=> feat: Adds custom headers to GatekeeperClient

packages/gatekeeper/src/db/abstract-json.ts, tests/gatekeeper/utils.test.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/1021
=> chore: gatekeeper fix race condition in JSON DB

apps/android/src/components/AuthTab.tsx, apps/android/src/components/HeldTab.tsx, apps/android/src/utils/utils.ts
- Resolves: https://github.com/KeychainMDIP/kc/issues/1034
=> feat: android scan credential QR code

packages/keymaster/src/types.ts, tests/keymaster/wallet.test.ts
This PR enables wallet metadata by adding support for arbitrary fields in wallet and ID information structures. The changes allow users to store custom metadata alongside standard wallet data and ensure this metadata persists through save/load and backup/recovery operations.
-    Added catch-all index signatures to support arbitrary metadata fields
-    Added test coverage for saving and recovering wallets with custom metadata
-    Verified metadata persistence across wallet backup and recovery operations
=> feat: Enables wallet metadata
